/** Mock data for My MLAs — trainees promoted after ~1 year, still mentored. */

import { mentors, type Mentor } from '../Trainees/traineesMockData';

export type { Mentor };
export { mentors };

export type MlaStatus = 'Active' | 'Inactive';

export type Mla = {
  id: string;
  mentorId: string;
  name: string;
  email: string;
  doj: string;
  billingPercent: number;
  scanCount: number;
  doex: string;
  status: MlaStatus;
  role: string;
};

export const mlas: Mla[] = [
  {
    id: 'm1',
    mentorId: 'mentor-madhu',
    name: 'Anita Joseph',
    email: 'anita.j@midna.com',
    doj: '12 Mar 2025',
    billingPercent: 35,
    scanCount: 120,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm2',
    mentorId: 'mentor-madhu',
    name: 'Farhan Ali',
    email: 'farhan.a@midna.com',
    doj: '08 Jun 2025',
    billingPercent: 40,
    scanCount: 85,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm3',
    mentorId: 'mentor-madhu',
    name: 'Geetha Krishnan',
    email: 'geetha.k@midna.com',
    doj: '02 Jan 2025',
    billingPercent: 28,
    scanCount: 40,
    doex: '—',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm4',
    mentorId: 'mentor-madhu',
    name: 'Imran Khan',
    email: 'imran.k@midna.com',
    doj: '19 Nov 2024',
    billingPercent: 20,
    scanCount: 22,
    doex: '05 Dec 2025',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm5',
    mentorId: 'mentor-priya',
    name: 'Nisha Varghese',
    email: 'nisha.v@midna.com',
    doj: '14 Feb 2025',
    billingPercent: 45,
    scanCount: 156,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm6',
    mentorId: 'mentor-priya',
    name: 'Arun Thomas',
    email: 'arun.t@midna.com',
    doj: '30 Apr 2025',
    billingPercent: 38,
    scanCount: 98,
    doex: '—',
    status: 'Active',
    role: 'MLA Counsellor',
  },
  {
    id: 'm7',
    mentorId: 'mentor-priya',
    name: 'Sneha George',
    email: 'sneha.g@midna.com',
    doj: '11 Sep 2024',
    billingPercent: 22,
    scanCount: 31,
    doex: '—',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm8',
    mentorId: 'mentor-arjun',
    name: 'Kavya Sundaram',
    email: 'kavya.s@midna.com',
    doj: '07 May 2025',
    billingPercent: 50,
    scanCount: 210,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm9',
    mentorId: 'mentor-arjun',
    name: 'Pradeep Rajan',
    email: 'pradeep.r@midna.com',
    doj: '21 Dec 2024',
    billingPercent: 30,
    scanCount: 74,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm10',
    mentorId: 'mentor-rathina',
    name: 'Saranya Devi',
    email: 'saranya.d@midna.com',
    doj: '03 Mar 2025',
    billingPercent: 42,
    scanCount: 143,
    doex: '—',
    status: 'Active',
    role: 'Senior MLA',
  },
  {
    id: 'm11',
    mentorId: 'mentor-rathina',
    name: 'Vignesh Kumar',
    email: 'vignesh.k@midna.com',
    doj: '16 Aug 2024',
    billingPercent: 25,
    scanCount: 55,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm12',
    mentorId: 'mentor-rathina',
    name: 'Lavanya R',
    email: 'lavanya.r@midna.com',
    doj: '28 Oct 2024',
    billingPercent: 18,
    scanCount: 18,
    doex: '20 Jun 2026',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm13',
    mentorId: 'mentor-riya',
    name: 'Mohamed Irfan',
    email: 'mohamed.i@midna.com',
    doj: '09 Jan 2025',
    billingPercent: 33,
    scanCount: 90,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm14',
    mentorId: 'mentor-riya',
    name: 'Aishwarya S',
    email: 'aishwarya.s@midna.com',
    doj: '22 Jun 2025',
    billingPercent: 27,
    scanCount: 47,
    doex: '—',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm15',
    mentorId: 'mentor-suresh',
    name: 'Naveen Shetty',
    email: 'naveen.s@midna.com',
    doj: '15 Apr 2025',
    billingPercent: 48,
    scanCount: 175,
    doex: '—',
    status: 'Active',
    role: 'MLA Counsellor',
  },
  {
    id: 'm16',
    mentorId: 'mentor-suresh',
    name: 'Rekha Pai',
    email: 'rekha.p@midna.com',
    doj: '04 Nov 2024',
    billingPercent: 36,
    scanCount: 110,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm17',
    mentorId: 'mentor-lakshmi',
    name: 'Siddharth Rao',
    email: 'siddharth.r@midna.com',
    doj: '18 Feb 2025',
    billingPercent: 29,
    scanCount: 66,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm18',
    mentorId: 'mentor-lakshmi',
    name: 'Padma Iyer',
    email: 'padma.i@midna.com',
    doj: '29 Jul 2024',
    billingPercent: 15,
    scanCount: 12,
    doex: '12 Apr 2026',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm19',
    mentorId: 'mentor-gopal',
    name: 'Ramesh Nair',
    email: 'ramesh.n@midna.com',
    doj: '11 May 2025',
    billingPercent: 52,
    scanCount: 188,
    doex: '—',
    status: 'Active',
    role: 'Senior MLA',
  },
  {
    id: 'm20',
    mentorId: 'mentor-gopal',
    name: 'Anjali Menon',
    email: 'anjali.m@midna.com',
    doj: '06 Sep 2024',
    billingPercent: 31,
    scanCount: 82,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm21',
    mentorId: 'mentor-neha',
    name: 'Rohit Mehta',
    email: 'rohit.m@midna.com',
    doj: '20 Mar 2025',
    billingPercent: 24,
    scanCount: 53,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm22',
    mentorId: 'mentor-neha',
    name: 'Priyanka Deshmukh',
    email: 'priyanka.d@midna.com',
    doj: '02 Dec 2024',
    billingPercent: 19,
    scanCount: 29,
    doex: '—',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm23',
    mentorId: 'mentor-karthik',
    name: 'Tejaswi Reddy',
    email: 'tejaswi.r@midna.com',
    doj: '13 Jan 2025',
    billingPercent: 44,
    scanCount: 134,
    doex: '—',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm24',
    mentorId: 'mentor-karthik',
    name: 'Chaitanya Varma',
    email: 'chaitanya.v@midna.com',
    doj: '27 Aug 2024',
    billingPercent: 37,
    scanCount: 95,
    doex: '—',
    status: 'Active',
    role: 'MLA Counsellor',
  },
];

export function mlaCountFor(mentorId: string): number {
  return mlas.filter((m) => m.mentorId === mentorId).length;
}
