/** Mock data for My MLAs — trainees promoted after ~1 year, still mentored. */

import { mentors, type Mentor } from '../Trainees/traineesData';

export type { Mentor };
export { mentors };

export type MlaStatus = 'Active' | 'Inactive' | 'Pending';

export type Mla = {
  id: string;
  mentorId: string;
  name: string;
  email: string;
  lastActive: string;
  promotedOn: string;
  status: MlaStatus;
  role: string;
};

export const mlas: Mla[] = [
  {
    id: 'm1',
    mentorId: 'mentor-madhu',
    name: 'Anita Joseph',
    email: 'anita.j@midna.com',
    lastActive: '26 Jul 2026',
    promotedOn: '12 Mar 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm2',
    mentorId: 'mentor-madhu',
    name: 'Farhan Ali',
    email: 'farhan.a@midna.com',
    lastActive: '24 Jul 2026',
    promotedOn: '08 Jun 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm3',
    mentorId: 'mentor-madhu',
    name: 'Geetha Krishnan',
    email: 'geetha.k@midna.com',
    lastActive: '18 Jul 2026',
    promotedOn: '02 Jan 2025',
    status: 'Pending',
    role: 'MLA Member',
  },
  {
    id: 'm4',
    mentorId: 'mentor-madhu',
    name: 'Imran Khan',
    email: 'imran.k@midna.com',
    lastActive: '10 Jul 2026',
    promotedOn: '19 Nov 2024',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm5',
    mentorId: 'mentor-priya',
    name: 'Nisha Varghese',
    email: 'nisha.v@midna.com',
    lastActive: '27 Jul 2026',
    promotedOn: '14 Feb 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm6',
    mentorId: 'mentor-priya',
    name: 'Arun Thomas',
    email: 'arun.t@midna.com',
    lastActive: '22 Jul 2026',
    promotedOn: '30 Apr 2025',
    status: 'Active',
    role: 'MLA Counsellor',
  },
  {
    id: 'm7',
    mentorId: 'mentor-priya',
    name: 'Sneha George',
    email: 'sneha.g@midna.com',
    lastActive: '15 Jul 2026',
    promotedOn: '11 Sep 2024',
    status: 'Pending',
    role: 'MLA Member',
  },
  {
    id: 'm8',
    mentorId: 'mentor-arjun',
    name: 'Kavya Sundaram',
    email: 'kavya.s@midna.com',
    lastActive: '25 Jul 2026',
    promotedOn: '07 May 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm9',
    mentorId: 'mentor-arjun',
    name: 'Pradeep Rajan',
    email: 'pradeep.r@midna.com',
    lastActive: '20 Jul 2026',
    promotedOn: '21 Dec 2024',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm10',
    mentorId: 'mentor-rathina',
    name: 'Saranya Devi',
    email: 'saranya.d@midna.com',
    lastActive: '28 Jul 2026',
    promotedOn: '03 Mar 2025',
    status: 'Active',
    role: 'Senior MLA',
  },
  {
    id: 'm11',
    mentorId: 'mentor-rathina',
    name: 'Vignesh Kumar',
    email: 'vignesh.k@midna.com',
    lastActive: '19 Jul 2026',
    promotedOn: '16 Aug 2024',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm12',
    mentorId: 'mentor-rathina',
    name: 'Lavanya R',
    email: 'lavanya.r@midna.com',
    lastActive: '12 Jul 2026',
    promotedOn: '28 Oct 2024',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm13',
    mentorId: 'mentor-riya',
    name: 'Mohamed Irfan',
    email: 'mohamed.i@midna.com',
    lastActive: '26 Jul 2026',
    promotedOn: '09 Jan 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm14',
    mentorId: 'mentor-riya',
    name: 'Aishwarya S',
    email: 'aishwarya.s@midna.com',
    lastActive: '21 Jul 2026',
    promotedOn: '22 Jun 2025',
    status: 'Pending',
    role: 'MLA Member',
  },
  {
    id: 'm15',
    mentorId: 'mentor-suresh',
    name: 'Naveen Shetty',
    email: 'naveen.s@midna.com',
    lastActive: '27 Jul 2026',
    promotedOn: '15 Apr 2025',
    status: 'Active',
    role: 'MLA Counsellor',
  },
  {
    id: 'm16',
    mentorId: 'mentor-suresh',
    name: 'Rekha Pai',
    email: 'rekha.p@midna.com',
    lastActive: '17 Jul 2026',
    promotedOn: '04 Nov 2024',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm17',
    mentorId: 'mentor-lakshmi',
    name: 'Siddharth Rao',
    email: 'siddharth.r@midna.com',
    lastActive: '25 Jul 2026',
    promotedOn: '18 Feb 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm18',
    mentorId: 'mentor-lakshmi',
    name: 'Padma Iyer',
    email: 'padma.i@midna.com',
    lastActive: '14 Jul 2026',
    promotedOn: '29 Jul 2024',
    status: 'Inactive',
    role: 'MLA Member',
  },
  {
    id: 'm19',
    mentorId: 'mentor-gopal',
    name: 'Ramesh Nair',
    email: 'ramesh.n@midna.com',
    lastActive: '28 Jul 2026',
    promotedOn: '11 May 2025',
    status: 'Active',
    role: 'Senior MLA',
  },
  {
    id: 'm20',
    mentorId: 'mentor-gopal',
    name: 'Anjali Menon',
    email: 'anjali.m@midna.com',
    lastActive: '23 Jul 2026',
    promotedOn: '06 Sep 2024',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm21',
    mentorId: 'mentor-neha',
    name: 'Rohit Mehta',
    email: 'rohit.m@midna.com',
    lastActive: '26 Jul 2026',
    promotedOn: '20 Mar 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm22',
    mentorId: 'mentor-neha',
    name: 'Priyanka Deshmukh',
    email: 'priyanka.d@midna.com',
    lastActive: '16 Jul 2026',
    promotedOn: '02 Dec 2024',
    status: 'Pending',
    role: 'MLA Member',
  },
  {
    id: 'm23',
    mentorId: 'mentor-karthik',
    name: 'Tejaswi Reddy',
    email: 'tejaswi.r@midna.com',
    lastActive: '24 Jul 2026',
    promotedOn: '13 Jan 2025',
    status: 'Active',
    role: 'MLA Member',
  },
  {
    id: 'm24',
    mentorId: 'mentor-karthik',
    name: 'Chaitanya Varma',
    email: 'chaitanya.v@midna.com',
    lastActive: '19 Jul 2026',
    promotedOn: '27 Aug 2024',
    status: 'Active',
    role: 'MLA Counsellor',
  },
];

export function mlaCountFor(mentorId: string): number {
  return mlas.filter((m) => m.mentorId === mentorId).length;
}
